---
title: "Data test"
author: "Victor Mandela"
date: "October 17, 2019"
output:
  word_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(knitr)
setwd("C:/Users/user/Desktop/Tiny Toto")
question1 <- read_csv("question1.csv")
question2 <- read_csv("question2.csv")
que2 <- read_csv("que2.csv")
que3 <- read_csv("que3.csv")
que4 <- read_csv("que4.csv")
question5 <- read_csv("question5.csv")
question5$Start_date <- dmy(question5$Start_date)
question5$End_date <- dmy(question5$End_date)
```

This is a report for the questions of the data test from Tiny Totos Kenya.

## Solutions to question one


```{r echo=FALSE}
#question1 %>% slice(1:) %>% summarise_all()
kable(question1[1:4,], caption = "Column and Row averages.")
```

The table above shows the row and column averages.

## Solutions for question 2 

This are the solutions to question 1 part two about cumulative unit sales from January 2015 to December 2017. 

```{r pressure, echo=FALSE}
kable(question2[1:3,], caption = "Cumulative Unit sales.")
qplot(data= question2,aes(x=X1))
```


